### ISSUE TITLE
Newsgroup data TODO items

### ISSUE THREAD

**Issue by cscherrer** [hakaru-dev/hakaru#44]
- [x] Hierarchical names (currently `News` is toplevel)
- [ ] Fix hardcoded path for newsgroup directory
- [ ] Integrate @zaxtax 's code for pulling data as part of build
- [ ] Match McCallum's word-filtering rules
- [x] Add an easy way to subset the data - maybe set topic indices to include and max docs per topic

**Comment by cscherrer** [comment]
> The Newsgroups data set, collected by Ken Lang,
contains about 20,000 articles evenly divided among
20 UseNet discussion groups (Joachims 1997). Many
of the categories fall into confusable clusters; for ex-
ample, five of them are comp.* discussion groups, and
three of them discuss religion. When tokenizing this
data, we skip the UseNet headers (thereby discarding
the subject line); tokens are formed from contiguous al-
phabetic characters with no stemming. The resulting
vocabulary, after removing words that occur only once
or on a stoplist, has 42191 words.

1. There's no fancy stemming to worry about, and pulling off the headers should be very easy.
1. I don't yet see an explicit list of the stopwords used. Maybe [the list in this code](https://github.com/brendano/bow/blob/master/stopwords.c) is it?
1. They're definitely doing classification, so supervised learning, not clustering. This will be the biggest challenge, since we'll need to modify the code accordingly.

**Comment by cscherrer** [comment]
I've now done the following:
1. remove headers
1. remove stopwords
1. encode words as distinct `Int`s
1. remove words that only occur once
1. recode words to fill in the holes left by removing singletons

Following this same process, McCallum reports ending up with 42191 words. Instead, we have 65510. We're in the neighborhood, but not exact yet. We don't have an authoritative list of stopwords used by McCallum, so it's likely this is the problem.

**Comment by zaxtax** [comment]
Can this issue be closed now?

**Comment by JacquesCarette** [comment]
Is this issue still 'live' or relevant?

**Comment by ccshan** [comment]
Probably not...
